name: first_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  animated_text_kit: ^4.2.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  modal_progress_hud_nsn: ^0.4.0
  font_awesome_flutter: ^10.1.0
  fluttertoast: ^8.0.9
  google_sign_in: ^6.1.4
  provider: ^6.0.5
  rename: ^2.1.1
  flutter_facebook_auth: ^6.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/firstchat_logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
